Projections - trackEmittedStreams and config
RemoteMetering/geteventstore-promise pull request #92
Opened 2020-10-08 15:25 UTC by maniolias

# Issues

## TrackEmittedStreams

The current version of `geteventstore-promise` does not allow to set trackEmittedStreams parameter to true. This feature is usefull when we want to delete a projection and it's emitted streams.

## GetInfo

To be able to test and validate the previous feature I've added the projection getInfo feature to add configuration informations.

2020-10-09 11:22 UTC, mmuller99 requested changes
Hi @maniolias , thanks for another good PR, I appreciate it! Please see comments

2020-10-09 11:22 UTC, mmuller99 commented on README.md
> +    Should track the emitted streams (used when we want delete the emitted streams when we delete the projection), defaults to false
```suggestion
    Should track the emitted streams (tracking emitted streams enables you to delete a projection and all the streams that it has created), defaults to false
```

2020-10-09 11:22 UTC, mmuller99 commented on lib/httpClient/projections/getInfo.js
> +	return { ...projectionInfo, ...{ config: projectionConfig } };
Can you please move this config call to its own method: `projections.config`?  And then extend this method (`getInfo`) to have a boolean `includeConfig` where we can extend the `info` results?

2020-10-09 11:22 UTC, mmuller99 commented on tests/http.projections.js
> +			assert.equal(responseWithTrackEmittedStreamsEnabled.config.emitEnabled, true);
```suggestion
			assert.equal(responseWithTrackEmittedStreamsEnabled.config.trackEmittedStreams, true);
```

2020-10-09 11:22 UTC, mmuller99 commented on tests/http.projections.js
> +			assert.equal(responseWithEmitEmittedStreamsEnabled.config.trackEmittedStreams, true);
Should be `false` if we remove the above test.
```suggestion
			assert.equal(responseWithEmitEmittedStreamsEnabled.config.trackEmittedStreams, false);
```

2020-10-12 08:03 UTC, maniolias commented
Hi,

Thanks for your feedback. I had to do more changes than expected. We cannot edit `trackEmittedStreams` configuration without calling the `config` route of the projection and we cannot do it when the projection is still running. For now I removed the editing of `trackEmittedStreams` parameters and will look to create the feature in a next PR.

2020-10-14 10:10 UTC, mmuller99 requested changes
Thanks for the changes and explanation @maniolias.  As a last request, can you please add a test for the newly added `projections.config` call as well as add it to the `README`?

2020-10-14 10:15 UTC, maniolias commented
Of course. My bad I missed this part. I'll look to do it ASAP.

2020-10-20 10:05 UTC, maniolias commented
I just did the changes you asks for. Hope it's good for you :).

2020-10-20 14:17 UTC, mmuller99 requested changes
Thanks @maniolias , last changes :)

2020-10-20 14:17 UTC, mmuller99 commented on README.md
> +    Object used to specify the partition to query the state for eg. `{ partition: 1}`
```suggestion
    Object, `partition` used to specify the partition to query the state with. e.g. `{ partition: 1 }`
```

2020-10-20 15:01 UTC, maniolias commented on README.md
> +    Object used to specify the partition to query the state for eg. `{ partition: 1}`
Thanks and sorry for my poor English :)

2020-10-20 15:03 UTC, maniolias commented
@mmuller99 thanks for your feedback. I did the expected changes in the README

2020-10-20 15:22 UTC, mmuller99 commented
@maniolias don't see the commit, can you please check?

2020-10-20 15:24 UTC, maniolias commented
Sorry, I didn't add it so push did nothing. It should be good now.

2020-10-20 15:30 UTC, mmuller99 approved these changes
Thanks @maniolias

2020-10-20 15:31 UTC, merged